modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="epicfightphystweaks"
version="${mod_version}"
displayName="${mod_name}"
description='''${mod_description}'''
authors="${mod_authors}"

[[dependencies.epicfightphystweaks]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="CLIENT"

[[dependencies.epicfightphystweaks]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="CLIENT"

[[dependencies.epicfightphystweaks]]
    modId="epicfight"
    mandatory=true
    versionRange="[20.0.0,)"
    ordering="AFTER"
    side="CLIENT"
